### ISSUE TITLE
新手遇到问题 Couldn't find preset "es2015" relative to directory 

### ISSUE THREAD

**Issue by ShawZG** [94dreamer/webpack#3]
非常有心啊，太赞了。
我在用webpack这个工具时遇到了问题，无法解决，能否帮忙瞅一眼呢？谢谢啦。

我对前端技术不了解，刚接触一个开源项目[html5_rtsp_player](https://github.com/SpecForge/html5_rtsp_player)，里面的demo中，有这个步骤”webpack --config webpack.config.js”，目前卡在了这里。
我在他们的项目中也提了[issu](https://github.com/SpecForge/html5_rtsp_player/issues/22)把自己遇到的问题及解决办法记录下来，但是维护人员估计很忙，一直没有回复我。
现在的报错是
Hash: c848527f64a5353b8e14
Version: webpack 1.13.3
Time: 527ms
    + 1 hidden modules
ERROR in ./test.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/home/shaw/workspace/html5_rtsp_player"
网上各种方法都看了，但是由于不了解webpack，只能胡乱尝试，都无法解决这个报错问题。

我的webpack.config.js文件内容如下：

const path = require('path');

const PATHS = {
    src: {
        test: path.join(__dirname, 'test.js')
    },
    dist: __dirname
};

module.exports = {
    entry: PATHS.src,
    output: {
        path: PATHS.dist,
        filename: '[name].bundle.js'
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                loader: 'babel',
                query: {
                    presets: ['es2015', 'stage-3', 'stage-2', 'stage-1', 'stage-0']
                }
            }
        ]
    },
    resolve: {
        alias: {
            rtsp: path.join(__dirname,'node_modules/html5_rtsp_player/src')
        }
    }
};

**Comment by ShawZG** [comment]
网上查到的方法都是下载es2015文件或是npm install命令下载所有的文件。对我这个问题都不管用。

**Comment by 94dreamer** [comment]
presets: ['es2015', 'stage-3', 'stage-2', 'stage-1', 'stage-0']

这一段你可能需要替换成"presets": ["es2015", "stage-0"]或者"presets": ["es2015", "stage-2"]。
stage-0语法比较宽松，另外检查下npm包的依赖，在package.json下是否有 
"babel-preset-es2015": "^6.6.0",
 "babel-preset-stage-2": "^6.5.0",
"babel-preset-stage-3": "^6.5.0",
"babel-preset-stage-1": "^6.5.0"
"babel-preset-stage-0": "^6.5.0"的依赖和安装。

**Comment by ShawZG** [comment]
非常感谢你的帮忙，按照你的提示，把presets: ['es2015', 'stage-3', 'stage-2', 'stage-1', 'stage-0']
替换成"presets": ["es2015", "stage-0"]了，
仍然提示：
ERROR in ./test.js
Module build failed: Error: Couldn't find preset "**es2015**" relative to directory "/home/shaw/workspace/html5_rtsp_player"

package.json文件所有内容如下：
{
  "name": "html5_rtsp_player.js.example",
  "version": "0.0.1",
  "private": true,
  "devDependencies": {
    "babel-core": "^6.18.2",
    "babel-loader": "^6.2.7",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-stage-0": "^6.5.0",
    "babel-preset-stage-1": "^6.5.0",
    "babel-preset-stage-2": "^6.5.0",
    "babel-preset-stage-3": "^6.5.0",
    "gulp": "^3.9.0",
    "gulp-babel": "^6.1.0",
    "gulp-concat": "^2.6.0",
    "gulp-load-plugins": "^1.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-uglify": "^1.4.2",
    "gulp-wrap": "^0.11.0",
    "webpack": "^1.12.14"
  },
  "dependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.18.2",
    "babel-loader": "^6.2.7",
    "babel-preset-es2015": "^6.18.0",
    "bp_event": "^1.0.1",
    "bp_logger": "^1.0.3",
    "bp_statemachine": "^1.0.0",
    "html5_rtsp_player": "*"
  }
}

我根据package.json的内容，尝试安装一些依赖
shaw@ubuntu:~/workspace/html5_rtsp_player/examples$ npm install babel-preset-es2015
html5_rtsp_player.js.example@0.0.1 /home/shaw/workspace/html5_rtsp_player/examples
└── babel-cli@6.18.0  extraneous
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15

shaw@ubuntu:~/workspace/html5_rtsp_player/examples$ npm install babel-preset-stage-0
html5_rtsp_player.js.example@0.0.1 /home/shaw/workspace/html5_rtsp_player/examples
└── babel-cli@6.18.0  extraneous
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15

shaw@ubuntu:~/workspace/html5_rtsp_player/examples$ npm install babel-core
html5_rtsp_player.js.example@0.0.1 /home/shaw/workspace/html5_rtsp_player/examples
└── babel-cli@6.18.0  extraneous
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15

shaw@ubuntu:~/workspace/html5_rtsp_player/examples$ npm install babel-loader
html5_rtsp_player.js.example@0.0.1 /home/shaw/workspace/html5_rtsp_player/examples
├── babel-cli@6.18.0  extraneous
└── babel-loader@6.2.8 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15

请问这些WARN是否对我现在的问题有影响？
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15

**Comment by 94dreamer** [comment]
这个问题最好的办法就是依赖包删除 重新安装。
建议安装换成淘宝的镜像，不明白可以百度。
npm install -g cnpm --registry=https://registry.npm.taobao.org

**Comment by ShawZG** [comment]
非常感谢帮忙，按照你们的指导，我再试一试。

**Comment by ShawZG** [comment]
使用淘宝的镜像，删除依赖包，重新按照，可以解决问题，非常感谢！

**Comment by zpg0624** [comment]
11
